# Numpy >> Is an library in py which is used for maths
## numpy is faster than lists
## numpy is used for working with arrays.
## numpy is short for numerical python

In [4]:
import numpy as np


In [6]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [10]:
print(type(arr)) # checking datatype

<class 'numpy.ndarray'>


In [14]:
arr = np.array((1,2,10,3,4,5))  # converting tuple into array.
print(arr)
print(type(arr))

[ 1  2 10  3  4  5]
<class 'numpy.ndarray'>


# createing n dimesion array

In [20]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)
print('dimension',arr2.ndim) # ndim us used to check dimesnion.

[[1 2 3]
 [4 5 6]]
dimension 2


In [24]:
arr3 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr3)
print('dimension is ',arr3.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
dimension is  3


In [29]:
a = np.array(42)
print(a,a.ndim)

42 0


In [31]:
b = np.array([1,2,3,4,5])
print(b,b.ndim)

[1 2 3 4 5] 1


In [33]:
c = np.array([[1,2,3],[4,5,6]])
print(c,c.ndim)

[[1 2 3]
 [4 5 6]] 2


In [37]:
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(d,d.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]] 3


## ndmin >> is used to convert into 'x' amount of  dimension


In [46]:
e = np.array([1,2,3,4],ndmin=5)
print(e)

[[[[[1 2 3 4]]]]]


In [56]:
# convert [1,2,3,4] into 6 dimesnison array
f = np.array([1,2,3,4],ndmin=6)
print(f,f.ndim)

[[[[[[1 2 3 4]]]]]] 6


In [58]:
# convert [[1,2,3,4,]] into 9 dimesnion array
h = np.array([1,2,3,4],ndmin=9)
print(h,h.ndim)

[[[[[[[[[1 2 3 4]]]]]]]]] 9


In [64]:
# check the dimesinon of [[[[12,34,45]]]
g = np.array([[[[12,34,45]]]])
print(g,g.ndim)

[[[[12 34 45]]]] 4


In [67]:
# Acces array element indexing

In [75]:
j = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(j)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [77]:
# print (j[0,1]]
print(j[0,1])

2


In [81]:
# extract 4 form array
print(j[0,3])

4


In [83]:
# extract 8 from array
print(j[1,2])

8


In [85]:
# which element is in j[1,4]
print(j[1,4])

10


In [89]:
# extract 7 from array
print(j[1,1])

7


In [97]:
l = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])


In [101]:
# extract 7 from array
print(l[1,0,0])

7


In [103]:
# extract 5 from array
print(l[0,1,1])

5


In [107]:
# extract 11 from array
print(l[1,1,1])

11


In [111]:
# which element is on l[1,1,2]
print(l[1,1,2])

12


In [113]:
k = np.array([[[[[1,2,3],[4,5,6]]]]])

In [115]:
# extrct 5
print(k[0,0,0,1,1])

5


In [117]:
# extrct 3
print(k[0,0,0,0,2])

3


# Zeros

In [120]:
m = np.zeros([5,4])
m

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [124]:
# create a matrix with zeros having 7 columns and 5 rows
n = np.zeros([5,7])
n

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [126]:
m = np.ones([4,5],dtype = 'int')
m

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [138]:

o = np.ones([6,6],dtype = 'int')
o

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

# arrange()


In [144]:
arr1 = np.arange(10,21)
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [148]:
arr1 = np.arange(0,21,2)
arr1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

# genrate random numbers
# 1.random

In [157]:
from numpy import random
x = random.randint(100)
print(x)

21


# 2.rand >> for float

In [167]:
x = random.rand()
print(x)

0.1213844743718775


In [171]:
# generate a 1-d array containing 5 random
x = random.randint(100,size=(5))
print(x)

[58 56 30 16 10]


In [179]:
# give 5 random numbers between 10 to 40 
x = random.randint(10,40,size=(5))
print(x)

[16 19 11 27 13]


In [187]:
# give an array of 9 numbers randomly between 0 to 300.
x = random.randint(300,size=(9))
print(x)

[237 173 271 103  46 214  22 238   1]


In [189]:
# give an array of 10 numbers randomly between 40 and 60
x = random.randint(40,60,size=(10))
print(x)

[55 43 54 43 53 53 43 53 51 43]


In [191]:
''' generate a 2-d array with 3 rows,each row containing 5
random integers from 0 to 100 '''
x = random.randint(100,size=(3,5))
print(x)

[[32  5 87 83 54]
 [23 69  2 21 48]
 [69 99 15 39 70]]


In [193]:
''' create a 2 d array with 7 columns and 5 rows having 
random numbers betn 20 and 40'''
x = random.randint(20,40,size=(5,7))
print(x)

[[35 33 37 23 38 27 23]
 [21 21 28 39 38 33 28]
 [22 28 20 37 35 25 28]
 [35 33 35 35 28 34 25]
 [39 29 21 32 38 27 29]]


# shuffle

In [202]:
arr  = np.array([1,2,3,4,5])
random.shuffle(arr)
print(arr)

[4 1 2 5 3]


# identity() >> identity matrix is square matrix (rows=columns)
## 1 at diagonal position and rest 0

In [207]:
# create a identity matrix of 6x6
a = np.identity(6,dtype = 'int')
a

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

# matrix addition

In [210]:
a1 = np.array([[5,6],[7,8]])
a2 = np.array([[2,3],[4,5]])
a3 = np.add(a1,a2)
print(a3)

[[ 7  9]
 [11 13]]


In [212]:
''' create 2 arrays of 3x3 with random
intergers within range 10 to 40 and 60 to 80 and
add them '''
# array 1
a4 =  random.randint(10,40,size=(3,3))
print(a4)

[[20 37 34]
 [29 25 36]
 [36 19 38]]


In [214]:
# array 2
a5 = random.randint(60,80,size=(3,3))
print(a5)

[[77 72 63]
 [73 73 64]
 [60 73 79]]


In [216]:
# additon
a6 = np.add(a4,a5)
print(a6)

[[ 97 109  97]
 [102  98 100]
 [ 96  92 117]]


In [218]:
''' add two arrays both of 4x4 within range 10 and 100 '''
# array 1
a7 =  random.randint(10,100,size=(4,4))
print(a7)

[[54 81 88 88]
 [23 46 33 13]
 [73 70 82 23]
 [49 25 91 27]]


In [220]:
# array 2
a8 =  random.randint(10,100,size=(4,4))
print(a8)

[[13 20 68 31]
 [10 29 17 98]
 [61 99 30 36]
 [87 18 13 14]]


In [222]:
# addition
a9 = np.add(a7,a8)
print(a9)

[[ 67 101 156 119]
 [ 33  75  50 111]
 [134 169 112  59]
 [136  43 104  41]]


# multiplication

In [228]:
aa = np.multiply(a7,a8)
aa

array([[ 702, 1620, 5984, 2728],
       [ 230, 1334,  561, 1274],
       [4453, 6930, 2460,  828],
       [4263,  450, 1183,  378]])

In [264]:
''' multiply 2 arrays, 1 st array with 2 rows and 3 columns and 6 elements with random values less than 20 and 2 nd 
array with 3 columns and 2 rows and 6 element with random values less than 50'''
aa1 = random.randint(0,20,size=(2,3))
print(aa1)


[[17 19 18]
 [19 19  8]]


In [262]:
aa2 = random.randint(0,50,size=(2,3))
print(aa2)

[[ 5 25 13]
 [39  0 19]]


In [266]:
aa3 = np.multiply(aa1,aa2)
print(aa3)

[[ 85 475 234]
 [741   0 152]]
