In [7]:
import numpy as np

In [1]:

# create an array of 4x4 having only ones
# create an identity matrix of 5x5
# convert [[45,56,78]] to 6 dimension array
# convert [[[10,20]],[[30,40]],[[50,60]],[[70,80]]] to an array and extract 60
# extract 30
# extract 10
# shuffle the elements of array [12,23,34,45,56]
# create an array of 4 columns and 5 rows having random numbers from 30 to 50
# add 2 arrays of 3x3 having random integers from 10 to 60 and 40 to 70
# multiply an identity matrix of 3x3 with an array of 3x3 having random integers from 10 to 30

In [33]:
# create an array of 4x4 having only ones
from numpy import random
x = random.randint(100,size=(4,4))
print(x)

[[69 28 18 47]
 [70 70 17 27]
 [62 80 48 13]
 [54 82 77 71]]


In [37]:
# create an identity matrix of 5x5
a = np.identity(5,dtype='int')
print(a)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [49]:
# convert [[45,56,78]] to 6 dimension array
b = np.array([45,56,78],ndmin=6)
print(b)


[[[[[[45 56 78]]]]]]


In [51]:
# convert [[[10,20]],[[30,40]],[[50,60]],[[70,80]]] to an array and extract 60
c = np.array([[[10,20]],[[30,40]],[[50,60]],[[70,80]]])
print(c)

[[[10 20]]

 [[30 40]]

 [[50 60]]

 [[70 80]]]


In [71]:
print(c[1,3,0])

IndexError: index 3 is out of bounds for axis 1 with size 1

In [75]:
# extract 30
print(c[0,1,0])

IndexError: index 1 is out of bounds for axis 1 with size 1

In [13]:
# extract 10

In [77]:
# shuffle the elements of array [12,23,34,45,56]
d = np.array([12,23,34,45,56])
random.shuffle(d)
print(d)

[45 56 12 23 34]


In [81]:
# create an array of 4 columns and 5 rows having random numbers from 30 to 50
a7 =  random.randint(30,50,size=(5,4))
print(a7)

[[49 34 31 41]
 [40 34 35 48]
 [44 30 35 45]
 [33 39 40 35]
 [39 36 36 47]]


In [19]:
# add 2 arrays of 3x3 having random integers from 10 to 60 and 40 to 70


In [21]:
# multiply an identity matrix of 3x3 with an array of 3x3 having random integers from 10 to 30

# Dot >> is used for matrix multiplication

In [87]:
a1 =  random.randint(10,20,size=(3,3))
print(a1)

[[12 18 19]
 [12 15 17]
 [18 11 12]]


In [85]:
a2 =  random.randint(30,40,size=(3,3))
print(a2)

[[36 36 32]
 [35 39 38]
 [39 30 31]]


In [91]:
a3 = np.dot(a1,a2)
print(a3)

[[1803 1704 1657]
 [1620 1527 1481]
 [1501 1437 1366]]


In [98]:
''' calculate the dot product of a matrix having 4 columns and 5 rows in 1st matrix
and 4 rows and 7 columns in 2nd matrix both having random values in range 40 to 50 '''
a4 = random.randint(40,50,size=(5,4))
print(a4)

a5 = random.randint(40,50,size=(4,7))
print(a5)

a6 = np.dot(a4,a5)
print(a6)

[[42 46 41 49]
 [44 45 42 42]
 [42 41 45 44]
 [46 45 41 40]
 [40 47 41 45]]
[[43 43 45 44 41 42 40]
 [41 40 48 40 49 46 42]
 [47 49 44 49 40 45 46]
 [45 48 46 46 48 40 41]]
[[7824 8007 8156 7951 7968 7685 7507]
 [7601 7766 7920 7726 7705 7488 7304]
 [7582 7763 7862 7717 7643 7435 7276]
 [7550 7707 7874 7673 7651 7447 7256]
 [7599 7769 7930 7719 7743 7487 7305]]


In [125]:
''' calcultate the dot product of matrix having only one of 2 columns and 3 rows in first matrix 
and 2nd matrix is identity matrix containing 4 elements '''

a7 = random.randint((3,2),dtype='int')
print(a7)

a8 = np.identity(100,size=(2,2))
print(a8)

a9 = np.dot(a7,a8)
print(a9)

[0 0]


TypeError: identity() got an unexpected keyword argument 'size'

# Append 


In [118]:
arr1 = np.array([2,3,4,5,6])
arr2 = np.append(arr1,100)
print(arr1)
print(arr2)

[2 3 4 5 6]
[  2   3   4   5   6 100]


In [120]:
arr1 = np.array([2,3,4,5,6])
arr2 = np.append(arr1,[200,300])
print(arr1)
print(arr2)

[2 3 4 5 6]
[  2   3   4   5   6 200 300]


# axis >> used for join >> 1. axis = 0 for below line and 2. axis = 1  >> current line

In [131]:
arr3 = np.array([[2,3,4],[5,6,7]])
arr4 = np.append(arr1,[[10,20,30]],axis = 0)
print(arr3)
print(arr4)

[[2 3 4]
 [5 6 7]]
[[ 2  3  4]
 [ 5  6  7]
 [10 20 30]]


In [145]:
arr5 = np.array([[2,3,4],[5,6,7]])
arr6 = np.append(arr1,[[10,20,30],[100,200,300]],axis = 1)
print(arr6)

[[  2   3   4  10  20  30]
 [  5   6   7 100 200 300]]


# concatente >> adding two array

In [155]:
arr7 = np.array([2,3,4])
arr8 = np.array([10,20,30])

new_arr =np.concatenate([arr7,arr8])
print('new array is ;',new_arr)

new array is ; [ 2  3  4 10 20 30]


In [174]:
arr9 = np.array([[2,3],[4,5]])
arr10 = np.array([[10,20],[30,40]])

new_arr1 =np.concatenate([arr9,arr10],axis = 1)
print('new array is /n ;',new_arr1)

new array is /n ; [[ 2  3 10 20]
 [ 4  5 30 40]]


In [166]:
arr11 = np.array([[2,3],[4,5]])
arr12 = np.array([[10,20],[30,40]])
arr13 = np.array([[100,200],[300,400]])
new_arr2 =np.concatenate([arr11,arr12,arr13])
print('new array is ;',new_arr2)

new array is ; [[  2   3]
 [  4   5]
 [ 10  20]
 [ 30  40]
 [100 200]
 [300 400]]


# for loop on array

# 1.nditer() 

In [178]:
# 2d 
arr14 = np.array([[2,3],[4,5]])
for i in np.nditer(arr14):
    print(i)

2
3
4
5


In [182]:
arr14 = np.random.randint(100,size=(5,6))
for i in np.nditer(arr14):
    print(i)

64
76
15
91
83
65
9
57
69
27
54
20
76
82
90
94
69
40
66
10
65
88
29
73
49
51
41
18
12
76


In [184]:
# 3 d
arr15 = np.array([[[2,3],[4,5]],[[20,30],[40,50]]])
for i in np.nditer(arr15):
    print(i)

2
3
4
5
20
30
40
50


# 2.ndenumerate()  >> gives index number and element

In [187]:
arr16 = np.array([2,3,4,5])
for i,value in np.ndenumerate(arr16):
    print(i,value)

(0,) 2
(1,) 3
(2,) 4
(3,) 5


In [191]:
arr17 = np.array([[[2,3],[4,5]],[[20,30],[40,50]]])
for i,value in np.ndenumerate(arr17):
    print(i,value)

(0, 0, 0) 2
(0, 0, 1) 3
(0, 1, 0) 4
(0, 1, 1) 5
(1, 0, 0) 20
(1, 0, 1) 30
(1, 1, 0) 40
(1, 1, 1) 50


In [195]:
# show the index number of all elements of array [[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]
arr18 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for i,value in np.ndenumerate(arr18):
    print(i,value)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(1, 0, 0) 7
(1, 0, 1) 8
(1, 0, 2) 9
(1, 1, 0) 10
(1, 1, 1) 11
(1, 1, 2) 12


# stastics

## 1.mean

mean = sum of values/number of values


In [204]:
arr19 = np.array([12,21,23,34,12])
mean = np.mean(arr19)
print('Mean of an array is :',mean)

Mean of an array is : 20.4


## 2 median

In [207]:
median = np.median(arr19)
print('Median of an array is :',median)

Median of an array is : 21.0


## 3.variance

In [210]:
variance = np.var(arr19)
print('Variance of an array is :',variance)

Variance of an array is : 66.63999999999999


## 4. std >> used for standard aviation

In [213]:
std = np.std(arr19)
print(std)

8.16333265278342


## 5.mode >> mode is not present  in numpy 

In [5]:
from scipy import stats

arr20 = np.array([0,0,1,1,1,2,2])
mode = stats.mode(arr20)
print('Mode of an array is :',mode)

NameError: name 'np' is not defined

## 6 np.ceil >> retrun cloest integer greater than number

In [11]:
arr21 = np.array([5.2,3.5,4.7,9.1])
np.ceil(arr21)

array([ 6.,  4.,  5., 10.])

## 7  floor >> retrun previos integer 

In [14]:
arr22 = np.array([5.2,3.5,4.7,9.1])
np.floor(arr22)

array([5., 3., 4., 9.])

## 8.unique >> it will give unique number

In [21]:
arr23 = np.array([12,23,12,34,32])
np.unique(arr23)

array([12, 23, 32, 34])

# Liner Algerbra

In [26]:
''' 3X + 4Y = 10
    2X + 5Y = 15 ''''
A = np.array([[3,4],[2,5]])
B = np.array([10,15])

result = np.linalg.solve(A,B)
result

array([-1.42857143,  3.57142857])

In [28]:
''' x + y = 24
    2x + 3y = 18  '''
C = np.array([[1,1],[2,3]])
D = np.array([24,18])

r = np.linalg.solve(C,D)
print(r)

[ 54. -30.]


In [32]:
''' 2x + 3y + 5z = 15
    3x + 10y + 15z = 40
    5x - 2y + 7z = 20 '''
E = np.array([[2,3,5],[3,10,15],[5,-2,7]])
F = np.array([15,40,20])

REE = np.linalg.solve(E,F)
print(REE)

[1.95121951 0.85365854 1.70731707]


## log >> gives ans as a power

In [35]:
np.log(10) # natural log ,e = 2.71

2.302585092994046

In [38]:
np.log(5)

1.6094379124341003

In [40]:
np.log(1)

0.0

In [42]:
np.log([10,14,18,19,20])

array([2.30258509, 2.63905733, 2.89037176, 2.94443898, 2.99573227])

# Trignometry

In [45]:
# find sin30
np.sin(np.pi/6) # np.sin(30) #0.5

0.49999999999999994

In [53]:
# find sin45
np.sin(np.pi/4)

0.7071067811865476

In [59]:
np.tan(np.pi/3)

1.7320508075688767

## Degree To Radian >> deg2rad()

In [61]:
arr = np.array([0,30,45,60,90])
Radian = np.deg2rad(arr)
Radian

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

## Radian to Degree >> rad2deg()

In [65]:
Rad = np.array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])
deg = np.rad2deg(Rad)
deg

array([ 0.        , 30.00000025, 44.99999981, 59.99999993, 90.00000018])

# End of numpy